spring:
  application:
    name: cinemaster-app
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemaster-app
    username: root
    password: root1234

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false


